print("Escola de inglês JoWell Sant’ana")

print("Insira as notas dos alunos!")

print("Você está digitando as notas dos alunos impares!")

aluno_1 = int(input("Insira a nota do aluno 1"))
print("Você está digitando as notas dos alunos impares!")
aluno_3 = int(input("Insira a nota do aluno 3"))
print("Você está digitando as notas dos alunos impares!")
aluno_5 = int(input("Insira a nota do aluno 5"))
print("Você está digitando as notas dos alunos impares!")
aluno_7 = int(input("Insira a nota do aluno 7"))
print("Você está digitando as notas dos alunos impares!")
aluno_9 = int(input("Insira a nota do aluno 9"))
print("Você está digitando as notas dos alunos impares!")
aluno_11 = int(input("Insira a nota do aluno 11"))
print("Você está digitando as notas dos alunos impares!")
aluno_13 = int(input("Insira a nota do aluno 13"))
print("Você está digitando as notas dos alunos impares!")
aluno_15 = int(input("Insira a nota do aluno 15"))
print("Você está digitando as notas dos alunos impares!")
aluno_17 = int(input("Insira a nota do aluno 17"))
print("Você está digitando as notas dos alunos impares!")
aluno_19 = int(input("Insira a nota do aluno 19"))
print("Você está digitando as notas dos alunos impares!")
aluno_21 = int(input("Insira a nota do aluno 21"))
print("Você está digitando as notas dos alunos impares!")
aluno_23 = int(input("Insira a nota do aluno 23"))
print("Você está digitando as notas dos alunos impares!")
aluno_25 = int(input("Insira a nota do aluno 25"))
print("Você está digitando as notas dos alunos impares!")
aluno_27 = int(input("Insira a nota do aluno 27"))
print("Você está digitando as notas dos alunos impares!")
aluno_29 = int(input("Insira a nota do aluno 29"))
print("Você está digitando as notas dos alunos impares!")
aluno_31 = int(input("Insira a nota do aluno 31"))
print("Você está digitando as notas dos alunos impares!")
aluno_33 = int(input("Insira a nota do aluno 33"))
print("Você está digitando as notas dos alunos impares!")
aluno_35 = int(input("Insira a nota do aluno 35"))
print("Você está digitando as notas dos alunos impares!")
aluno_37 = int(input("Insira a nota do aluno 37"))
print("Você está digitando as notas dos alunos impares!")
aluno_39 = int(input("Insira a nota do aluno 39"))
print("Você está digitando as notas dos alunos impares!")
aluno_41 = int(input("Insira a nota do aluno 41"))
print("Você está digitando as notas dos alunos impares!")
aluno_43 = int(input("Insira a nota do aluno 43"))
print("Você está digitando as notas dos alunos impares!")
aluno_45 = int(input("Insira a nota do aluno 45"))
print("Você está digitando as notas dos alunos impares!")
aluno_47 = int(input("Insira a nota do aluno 47"))
print("Você está digitando as notas dos alunos impares!")
aluno_49 = int(input("Insira a nota do aluno 49"))
print("Você finalizou as notas dos alunos impares")

print("Você está digitando a nota dos alunos pares!")

aluno_2 = int(input("Insira a nota do aluno 2"))
print("Você está digitando a nota dos alunos pares!")
aluno_4 = int(input("Insira a nota do aluno 4"))
print("Você está digitando a nota dos alunos pares!")
aluno_6 = int(input("Insira a nota do aluno 6"))
print("Você está digitando a nota dos alunos pares!")
aluno_8 = int(input("Insira a nota do aluno 8"))
print("Você está digitando a nota dos alunos pares!")
aluno_10 = int(input("Insira a nota do aluno 10"))
print("Você está digitando a nota dos alunos pares!")
aluno_12 = int(input("Insira a nota do aluno 12"))
print("Você está digitando a nota dos alunos pares!")
aluno_14 = int(input("Insira a nota do aluno 14"))
print("Você está digitando a nota dos alunos pares!")
aluno_16 = int(input("Insira a nota do aluno 16"))
print("Você está digitando a nota dos alunos pares!")
aluno_18 = int(input("Insira a nota do aluno 18"))
print("Você está digitando a nota dos alunos pares!")
aluno_20 = int(input("Insira a nota do aluno 20"))
print("Você está digitando a nota dos alunos pares!")
aluno_22 = int(input("Insira a nota do aluno 22"))
print("Você está digitando a nota dos alunos pares!")
aluno_24 = int(input("Insira a nota do aluno 24"))
print("Você está digitando a nota dos alunos pares!")
aluno_26 = int(input("Insira a nota do aluno 26"))
print("Você está digitando a nota dos alunos pares!")
aluno_28 = int(input("Insira a nota do aluno 28"))
print("Você está digitando a nota dos alunos pares!")
aluno_30 = int(input("Insira a nota do aluno 30"))
print("Você está digitando a nota dos alunos pares!")
aluno_32 = int(input("Insira a nota do aluno 32"))
print("Você está digitando a nota dos alunos pares!")
aluno_34 = int(input("Insira a nota do aluno 34"))
print("Você está digitando a nota dos alunos pares!")
aluno_36 = int(input("Insira a nota do aluno 36"))
print("Você está digitando a nota dos alunos pares!")
aluno_38 = int(input("Insira a nota do aluno 38"))
print("Você está digitando a nota dos alunos pares!")
aluno_40 = int(input("Insira a nota do aluno 40"))
print("Você está digitando a nota dos alunos pares!")
aluno_42 = int(input("Insira a nota do aluno 42"))
print("Você está digitando a nota dos alunos pares!")
aluno_44 = int(input("Insira a nota do aluno 44"))
print("Você está digitando a nota dos alunos pares!")
aluno_46 = int(input("Insira a nota do aluno 46"))
print("Você está digitando a nota dos alunos pares!")
aluno_48 = int(input("Insira a nota do aluno 48"))
print("Você está digitando a nota dos alunos pares!")
aluno_50 = int(input("Insira a nota do aluno 50"))
print("Você finalizou as notas dos alunos pares!")


soma1 = float(aluno_1 + aluno_3 + aluno_5 + aluno_7 + aluno_9 + aluno_11 + aluno_13 + aluno_15 + aluno_17 + aluno_19 + aluno_21 + aluno_23 + aluno_25 + aluno_27 + aluno_29 + aluno_31 + aluno_33 + aluno_35 + aluno_37 + aluno_39 + aluno_41 + aluno_43 + aluno_45 + aluno_47 + aluno_49)

soma2 = float(aluno_2 + aluno_4 + aluno_6 + aluno_8 + aluno_10 + aluno_12 + aluno_14 + aluno_16 + aluno_18 + aluno_20 + aluno_22 + aluno_24 + aluno_26 + aluno_28 + aluno_30 + aluno_32 + aluno_34 + aluno_36 + aluno_38 + aluno_40 + aluno_42 + aluno_44 + aluno_46 + aluno_48 + aluno_50)

média1 = (soma1)/25

média2 = (soma2)/25
print("A média dos alunos impares foi de {}".format(média1))
print("A média dos alunos pares foi de {}".format(média2))

if média1 > média2:
    print("Os alunos impares forma melhores!")

else:
    média1 < média2
    print("Os alunos pares foram melhores!")
